name: AKS Power Platform

on:
  push:
    branches: [ dev ]

permissions:
   id-token: write
   contents: read


jobs:
  DEV:
    uses: ./.github/workflows/bicep-istio-deployment.yml
    with:
      environment: development
    secrets:
      clientId: ${{ secrets.AZURE_CLIENT_ID }}
      tenantId: ${{ secrets.AZURE_TENANT_ID }}
      subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  PROD:
    needs: [DEV]
    uses: ./.github/workflows/bicep-istio-deployment.yml
    with:
      environment: production
    secrets:
      clientId: ${{ secrets.AZURE_CLIENT_ID }}
      tenantId: ${{ secrets.AZURE_TENANT_ID }}
      subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}