name: AKS Power Platform

on:
  push:
    branches: [ dev ]

permissions:
   id-token: write
   contents: read


jobs:
  ReuseableMatrixJobForDeployment:
    uses: DevOps-Global-Summit-22/aks-power/tree/main/.github/templates/bicep-deployment.yml@dev