name: AKS Power Platform

on:
  push:
    branches: [ dev ]

permissions:
   id-token: write
   contents: read


jobs:
  DEV_INFRA:
    uses: ./.github/workflows/bicep-deployment.yml
    with:
      environment: development
  DEV_SERVICE_MESH:
    needs: [DEV_INFRA]
    uses: ./.github/workflows/istio-deployment.yml
    with:
      environment: development
      aks_name: ${{ needs.DEV_INFRA.outputs.aks_name }}
      aks_resource_group: ${{ needs.DEV_INFRA.outputs.aks_resource_group }}

  PROD_INFRA:
    needs: [DEV_SERVICE_MESH]
    uses: ./.github/workflows/bicep-deployment.yml
    with:
      environment: production
  PROD_SERVICE_MESH:
    needs: [PROD_INFRA]
    uses: ./.github/workflows/istio-deployment.yml
    with:
      environment: production
      aks_name: ${{ needs.PROD_INFRA.outputs.aks_name }}
      aks_resource_group: ${{ needs.PROD_INFRA.outputs.aks_resource_group }}