name: AKS Power Platform

on:
  push:
    branches: [ dev ]

permissions:
   id-token: write
   contents: read


jobs:
  DEV:
    environment: development
      uses: ./.github/workflows/bicep-deployment.yml
      with:
        environment: development