name: AKS Power Platform

on:
  push:
    branches: [ dev ]

permissions:
   id-token: write
   contents: read


jobs:
  Developemnt:
    environment: development
    uses: ./.github/workflows/bicep-deployment.yml
    with:
      environment: development
  Production:
    environment: production
    uses: ./.github/workflows/bicep-deployment.yml
    with:
      environment: production