name: AKS Power Platform

on:
  push:
    branches: [ dev ]

permissions:
   id-token: write
   contents: read


jobs:
  ReuseableMatrixJobForDeployment:
    uses: ./.github/workflows/bicep-deployment.yml