name: Deploy Environment

on:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
        default: development

env:
  LOCATION: "westeurope"

jobs:
  bicep-whatif-deployment:
    name: 'Bicep Deployment'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Authenticate to Az CLI using OIDC
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: c45ab810-b8b0-4a2e-aabd-409af62461b7
        tenant-id: 16b3c013-d300-468d-ac64-7eda0820b6d3
        subscription-id: 4572a41c-c128-4e47-bbbc-19d1a188492d

    # Checks that all Bicep configuration files adhere to a canonical format
    - name: Bicep Lint
      uses: Azure/cli@v1
      with:
        inlineScript: az bicep build --file iac/deploy.bicep

    # Validate whether a template is valid at subscription scope
    - name: Bicep Validate
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az deployment sub validate \
            --name validate-${{ github.run_id }} \
            --template-file iac/deploy.bicep \
            --parameters iac/parameters/parameters.${{ inputs.environment }}.json \
            --location $LOCATION     
    # Preview changes
    - name: "What-If"
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az deployment sub what-if \
            --name whatif-${{ github.run_id }} \
            --template-file iac/deploy.bicep \
            --parameters iac/parameters/parameters.${{ inputs.environment }}.json \
            --location $LOCATION > whatif

    # Create string output of Whatif
    - name: Create String Output
      id: whatif-string
      run: |
        WHATIF=$(cat whatif)
        echo "## Whatif Output ${{ inputs.environment }}" >> whatif.string
        echo "<details><summary>Click to expand</summary>" >> whatif.string
        echo "" >> whatif.string
        echo '```' >> whatif.string
        echo "$WHATIF" >> whatif.string
        echo '```' >> whatif.string
        echo "</details>" >> whatif.string

        SUMMARY=$(cat whatif.string)
        SUMMARY="${SUMMARY//'%'/'%25'}"
        SUMMARY="${SUMMARY//$'\n'/'%0A'}"
        SUMMARY="${SUMMARY//$'\r'/'%0D'}"

        echo "::set-output name=summary::$SUMMARY"
    # Publish What-If output as a task summary
    - name: Publish Whatif to Task Summary
      run: |
        cat whatif.string >> $GITHUB_STEP_SUMMARY

    # Deploy
    - name: "Bicep Deployment"
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az deployment sub create \
            --name deploy-${{ github.run_id }} \
            --template-file iac/deploy.bicep \
            --parameters iac/parameters/parameters.${{ inputs.environment }}.json \
            --location $LOCATION 