name: Deploy Environment

on:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
        default: development
      aks_name:
        required: true
        type: string
      aks_resource_group:
        required: true
        type: string

env:
  LOCATION: "westeurope"

jobs:
  bicep-whatif-deployment:
    name: 'Bicep Deployment'
    runs-on: [self-hosted, Linux, X64]
    environment: ${{ inputs.environment }}
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Authenticate to Az CLI using OIDC
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: c41691de-b101-48df-8e46-6c75df67c83b
        tenant-id: b21d2602-445a-42f6-8657-9d684c04b21a
        subscription-id: b459ab19-8de5-413f-a279-55bcc620591b

    # Get AKS Credentials
    - name: Getting AKS Credentials
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az aks get-credentials \
            --resource-group ${{ inputs.aks_resource_group }}
            --name ${{ inputs.aks_name }}